#!/bin/bash

# List common PIA regions for use with the proxy farm

echo "Common PIA Regions (use with --country and --city flags):"
echo ""
echo "US Regions:"
echo "  pf add --country US --city Atlanta"
echo "  pf add --country US --city Chicago"
echo "  pf add --country US --city Dallas"
echo "  pf add --country US --city Denver"
echo "  pf add --country US --city 'Las Vegas'"
echo "  pf add --country US --city 'Los Angeles'"
echo "  pf add --country US --city Miami"
echo "  pf add --country US --city 'New York'"
echo "  pf add --country US --city Seattle"
echo "  pf add --country US --city 'Washington DC'"
echo ""
echo "European Regions:"
echo "  pf add --country UK --city London"
echo "  pf add --country UK --city Manchester"
echo "  pf add --country DE --city Berlin"
echo "  pf add --country DE --city Frankfurt"
echo "  pf add --country FR --city Paris"
echo "  pf add --country NL --city Amsterdam"
echo "  pf add --country CH --city Zurich"
echo ""
echo "Other Regions:"
echo "  pf add --country CA --city Toronto"
echo "  pf add --country CA --city Vancouver"
echo "  pf add --country AU --city Melbourne"
echo "  pf add --country AU --city Sydney"
echo "  pf add --country JP --city Tokyo"
echo ""
echo "Or just specify country to use any server there:"
echo "  pf add --country Netherlands"
echo "  pf add --country Germany"
echo "  pf add --country Switzerland"
echo ""
echo "Or omit both to auto-select fastest:"
echo "  pf add"